export const formations = [
{
    title: "Développement Web Fullstack",
    image: "/images/web-dev.jpg",
    points: [
      "HTML, CSS, JavaScript avancés",
      "Frameworks React & Node.js",
      "Bases de données relationnelles",
      "Déploiement et CI/CD",
    ],
    description: "Devenez un développeur web complet capable de créer des applications modernes de bout en bout. Cette formation couvre tous les aspects du développement web, du front-end au back-end.",
    duration: "6 mois",
    level: "Débutant à Intermédiaire",
    price: "150 000 FCFA",
  },
  {
    title: "Design Graphique & UI/UX",
    image: "/images/ui-ux.jpg",
    points: [
      "Principes du design visuel",
      "Figma, Adobe XD & Photoshop",
      "Recherche UX (User Experience)",
      "Prototypage et tests utilisateurs",
    ],
    description: "Maîtrisez les outils professionnels de design et créez des interfaces utilisateur intuitives et esthétiques. Apprenez à concevoir des expériences utilisateur mémorables.",
    duration: "4 mois",
    level: "Tous niveaux",
    price: "120 000 FCFA",
  },
  {
    title: "Maîtrise de la Bureautique",
    image: "/images/bureautique.jpg",
    points: [
      "Microsoft Office 365 (Word, Excel, PowerPoint)",
      "Gestion de projet (Asana, Trello)",
      "Communication professionnelle",
      "Optimisation de productivité",
    ],
    description: "Développez vos compétences en bureautique et augmentez votre productivité professionnelle. Formation pratique axée sur les outils utilisés en entreprise.",
    duration: "2 mois",
    level: "Débutant",
    price: "80 000 FCFA",
  },
  {
    title: "Marketing Digital",
    image: "/images/marketing.jpg",
    points: [
      "SEO (Search Engine Optimization)",
      "Publicité en ligne (Google Ads, Social Media)",
      "Analyse de données (Analytics)",
      "Stratégie de contenu",
    ],
    description: "Apprenez à promouvoir efficacement votre entreprise en ligne. Maîtrisez les stratégies de marketing digital pour générer du trafic et des conversions.",
    duration: "3 mois",
    level: "Intermédiaire",
    price: "100 000 FCFA",
  },
  {
    title: "Intelligence Artificielle",
    image: "/images/ai.jpg",
    points: [
      "Apprentissage automatique (Machine Learning)",
      "Modèles prédictifs et génératifs",
      "Projets pratiques et cas d'usage",
      "Éthique de l'IA et déploiement",
    ],
    description: "Plongez dans le monde de l'IA et du Machine Learning. Créez vos propres modèles d'IA et comprenez les enjeux éthiques de cette technologie révolutionnaire.",
    duration: "5 mois",
    level: "Avancé",
    price: "180 000 FCFA",
  },
  {
    title: "Cloud Computing",
    image: "/images/cloud.jpg",
    points: [
      "Fondamentaux AWS/GCP",
      "Déploiement d'applications cloud",
      "Infrastructure as Code (IaC)",
      "Sécurité et scalabilité cloud",
    ],
    description: "Maîtrisez les plateformes cloud AWS et GCP. Apprenez à déployer, gérer et sécuriser des infrastructures cloud professionnelles et évolutives.",
    duration: "4 mois",
    level: "Intermédiaire à Avancé",
    price: "140 000 FCFA",
  },
];
